const dataOrdering = {
    ru:{
        content1:"Оформление заказа",
        content2:"Доставка курьером",
        content3:"Адрес доставки",
        content4:"сўм",
        content5:"Город ",
        content6:"Улица / Район",
        content7:"Дом",
        content8:"Подъезд",
        content9:"Квартира",
        content10:"Ваш заказ",
        content11:"Доставка",
        content12:"К оплате",
        content13:"Способ оплаты",
        content14:"Тип платежа",
        content16:"Денежные средства",
        content17:"Oнлайн платеж",
        content18:"Номер получателя",
        content19:"Закончить оформление",
        content20:"Номер вашего заказа №",
        content21:" с Вами свяжется наш менеджер.",
    },
    en:{
        content1:"Checkout",
        content2:"Delivery by courier",
        content3:"Delivery address",
        content4:"sum",
        content5:"City",
        content6:"Street / Area",
        content7:"House",
        content8:"Entrance",
        content9:"Apartment",
        content10:"Your order",
        content11:"Delivery",
        content12:"Payable",
        content13:"Payment method",
        content14:"Payment type",
        content16:"Cash",
        content17:"Online payment",
        content18:"Recipient number",
        content19:"Finish design",
        content20:"Your order number №",
        content21:",  our manager will contact you.",
    },
    uz:{
         content1:"To'lov",
         content2:"Kuryer orqali yetkazib berish",
         content3:"Etkazib berish manzili",
         content4:"so'm",
         content5:"Shahar",
         content6:"Ko'cha / Hudud",
         content7:"Uy",
         content8:"Kirish",
         content9:"Kvartira",
         content10:"Buyurtmangiz",
         content11:"Etkazib berish",
         content12:"To'lanishi kerak",
         content13:"To'lov usuli",
         content14:"To'lov turi",
         content16:"Naqd pul",
         content17:"Onlayn to'lov",
         content18:"Qabul qiluvchining raqami",
         content19:"Dizaynni tugatish",
         content20:"Buyurtma raqamingiz №",
         content21:",  menejerimiz siz bilan bog'lanadi.",
    }
}

export default dataOrdering